### ISSUE TITLE
你好，请问有2024年的数据吗？

### ISSUE THREAD

**Issue by zy19991012z** [ChinaHolidays/ChinaHolidays#1]
你好，首先感谢您提供这份json，礼貌提问一下，这个项目后续会更新2026年的吗？如果不更新，可以大概介绍一下如何生成这种数据吗？可以有偿学习。

**Comment by ChinaHolidays** [comment]
2024年数据已经添加；后续，每年也都会更新。 如何生成这种数据，逻辑比较简单的，自己思考下呢或者去问问AI大模型。工作比较忙，麻烦不用再回复啊，谢谢。
